src/BandedMatrices.jl
test/runtests.jl

each babdedindex is now an iterator

Feat eachbandedindex

---

src/BandedMatrices.jl
src/blas.jl
test/runtests.jl

This changes banded matrices to use the standard column based ordering, so each column of B.data is a column of B

Column-based ordering

---

src/BandedMatrices.jl
src/blas.jl
test/runtests.jl
test/test_bandedlu.jl

OK, as promised here is a basic interface that serves most of the purposes. ~~Currently, it is not as flexible as the factorisation interface in base julia, (e.g. `A` and  `b` must have same types), but we can improve upon this as needed.~~ 
Fixes #3.

WIP: added banded LU factorisation and solution of banded linear systems

---

test/test_bandedlu.jl

I will try a couple of seed values until I find one for which tests pass

seed prng before testing the banded lu code

---

src/BandedMatrices.jl
test/runtests.jl
test/test_indexing.jl

Here is a pull request where I have implemented `setindex!`. The merge with upstream was a bit troublesome, so the diff generated by github is not really clear. Looking at the tests is probably a better way to see what was implemented. Please review this and let's discuss if anything needs to be changed.  
There are other methods that I need to implement, but this is the lowest basis.

RFC: Implemented `setindex`, fixes #5

---

test/test_bandedlu.jl

This is to be merged once https://github.com/JuliaLang/julia/pull/17389 gets into 0.5.

Remove special test for master

---

src/BandedCholesky.jl
src/BandedLU.jl
src/BandedMatrices.jl
src/SymBandedMatrix.jl
src/blas.jl
test/test_symbanded.jl

Not in any rush to merge this, just thought I'd give a head's up that this is the PR that will add these features.

Add symmetric-definite banded generalized eigenvalue overrides

---

docs/make.jl

since we are now v0.6 above only

deploy docs on julia v0.6

---

src/BandedMatrices.jl
src/symbanded/symbanded.jl
test/test_symbanded.jl

What is missing is checking that the returned eigenvectors are correct.

Added eigen for calculation of eigenvectors of symmetric banded matrices

---

REQUIRE
appveyor.yml
src/BandedMatrices.jl
src/banded/BandedMatrix.jl
src/banded/BandedQR.jl
src/banded/linalg.jl
src/generic/AbstractBandedMatrix.jl
src/generic/broadcast.jl
src/generic/indexing.jl
src/generic/matmul.jl
src/generic/utils.jl
src/interfaceimpl.jl
src/symbanded/symbanded.jl
src/tribanded.jl
test/test_bandedqr.jl
test/test_broadcasting.jl
test/test_indexing.jl
test/test_interface.jl
test/test_linalg.jl
test/test_subarray.jl
test/test_symbanded.jl
test/test_tribanded.jl

@jagot you might want to use this branch

WIP features to support ContinuumArrays.jl

---

src/BandedMatrices.jl
src/banded/BandedQR.jl
src/generic/utils.jl
test/test_bandedqr.jl

This uses `LinearAlgebra.QR` instead of creating `BandedQR`. It looks like there is a substantial speedup of 3x or so as well.

revamped QR

---

src/banded/BandedLU.jl
test/test_bandedlu.jl
test/test_tribanded.jl

Need the `LinearAlgebra` in front of `issuccess` to properly import the method.

Various LU/tbv methods

---

src/generic/AbstractBandedMatrix.jl
test/runtests.jl
test/test_miscs.jl

Added specialized bandwidths(A::SparseMatrixCSC)

---

.travis.yml
Project.toml
appveyor.yml
src/BandedMatrices.jl
src/banded/BandedMatrix.jl
src/generic/broadcast.jl
src/interfaceimpl.jl
src/symbanded/ldlt.jl
src/symbanded/symbanded.jl
test/test_banded.jl
test/test_broadcasting.jl
test/test_interface.jl
test/test_miscs.jl

This is needed when the data has a crazy type signature (as unfortunately is the case down stream in OrthogonalPolynomialsQuasi.jl)

More descriptive summary

---

Project.toml

version bump to v0.17.5

---

.github/workflows/ci.yml
.github/workflows/docs.yml

This PR fixes https://github.com/JuliaMatrices/BandedMatrices.jl/issues/249.

Fix `ci.yml` for versioned documentation

---

Project.toml
src/banded/bandedqr.jl
test/test_bandedlu.jl
test/test_bandedqr.jl

This is a companion PR to https://github.com/JuliaLang/julia/pull/46196.

Adjustments to `AbstractQ` intro in LinearAlgebra

---

test/test_banded.jl
test/test_bandedlu.jl
test/test_bandedqr.jl
test/test_symbanded.jl

Replace non-breaking spaces by regular spaces. No code change

Fix whitespace in tests

---

src/generic/broadcast.jl

`_banded_broadcast!` methods for `BandedColumn` are considerably large functions, and separating out the common parts and not inlining it actually helps with performance.
On master
```julia
julia> A = BandedMatrix(0=>Float64[1:30000;]); C = copy(A);
julia> @btime $C .= $A .* 2;
81.493 μs (0 allocations: 0 bytes)
```
This PR
```julia
julia> @btime $C .= $A .* 2;
75.632 μs (2 allocations: 48 bytes)
```
The two allocations arise because the function isn't inlined, but overall this seems pretty insignificant.
This also helps with TTFX:
On master
```julia
julia> A = BandedMatrix(0=>Float64[1:3000;]); C = copy(A);
julia> @time C .= A .* 2;
0.620778 seconds (893.19 k allocations: 59.337 MiB, 4.86% gc time, 99.90% compilation time)
julia> @time C .= 2 .* A;
0.535827 seconds (845.23 k allocations: …
```

Reduce code duplication in banded_broadcast

---

src/generic/matmul.jl
test/test_broadcasting.jl

This helps with TTFX
On master
```julia
julia> B = BandedMatrix(0=>ones(1000));
julia> v = ones(size(B,1));
julia> @time @eval B' * v;
1.284047 seconds (4.66 M allocations: 537.080 MiB, 7.13% gc time, 99.22% compilation time)
```
This PR
```julia
julia> @time @eval B' * v;
0.321558 seconds (784.08 k allocations: 52.189 MiB, 3.48% gc time, 96.75% compilation time)
```

Remove recursion in BlasMatMulVecAdd `materialize!`

---

src/generic/matmul.jl

All of these methods seem to do the same thing, so we may do with only one method.

consolidate bandwidth methods for Mul/MulAdd

---

src/generic/Band.jl

Use non-trivial examples in doctests

Improve band doctest examples

---

src/banded/BandedMatrix.jl

These should be handled by broadcast

don't specialize real/imag

---

docs/Project.toml

reorder deps in docs/Project.toml

---

src/banded/BandedMatrix.jl
test/test_banded.jl

After this, the following works:
```julia
julia> B = BandedMatrix(0=>1:4, 1=>5:7)
4×4 BandedMatrix{Int64} with bandwidths (0, 1):
1  5  ⋅  ⋅
⋅  2  6  ⋅
⋅  ⋅  3  7
⋅  ⋅  ⋅  4
julia> B[1, :] = 2 .* first(eachrow(B));
julia> B
4×4 BandedMatrix{Int64} with bandwidths (0, 1):
2  10  ⋅  ⋅
⋅   2  6  ⋅
⋅   ⋅  3  7
⋅   ⋅  ⋅  4
```

Fix assigning vector to row

---

src/generic/AbstractBandedMatrix.jl
test/test_symbanded.jl

These should make development easier

Docstrings for colrange/rowrange and friends

---

test/test_banded.jl

This should cover the missing tests in https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/pull/158

Tests for sparse copyto layoutmatrix

---

Project.toml
test/test_interface.jl

This was not being used anywhere

Remove Base64 from tests

---

docs/Project.toml
docs/make.jl
docs/src/index.md
src/generic/Band.jl

Also, add a few more docstrings to the manual.

Use Documenter v1 to build docs

---

.github/workflows/ci.yml

This should cache the dependencies and make the CI faster.

Use julia cache in CI

---

Project.toml

Bump compat for CliqueTrees to 1.
