JuliaLinearAlgebra/BandedMatrices.jl

src/BandedMatrices.jl
=> use RowVector only when it's defined in Base

.travis.yml
Make the build icon in the readme green again.
=> Allow failures on Julia nightly to get rid of the build error

src/banded/BandedMatrix.jl, test/test_banded.jl
Also, expanded the functonality to:
```Julia
similar(bm::BandedMatrix, [T::Type], [n::Integer, m::Integer, [l::Integer, u::Integer]])
similar(bm::BandedSubBandedMatrix, [T::Type], [n::Integer, m::Integer, [l::Integer, u::Integer]])
```
The view banded matrix matches the `convert(BandedMatrix, @view banded[...])`. @dlfivefifty, I don't pretend I understand exactly how the bands are stored, nor exactly what each field references. Please check!
=> similar is now aware of containers

README.md, docs/src/index.md
This PR removes the obsolete (no longer working) example from the README and adds a link to the documentation, where the finite-difference example from #65 is added.
=> Examples in README and documentation #65

src/lapack.jl, src/symbanded/BandedCholesky.jl, test/test_symbanded.jl
Prior to this PR, this is what I get:
```julia
julia> cholesky(B)
ERROR: MethodError: LinearAlgebra.cholesky!(::Symmetric{Float64,BandedMatrices.BandedMatrix{Float64,Array{Float64,2}}}) is ambiguous. Candidates:
cholesky!(A::Symmetric{T,#s100} where #s100<:BandedMatrices.BandedMatrix) where T<:Number in BandedMatrices at /Users/jagot/.julia/packages/BandedMatrices/2idIC/src/symbanded/BandedCholesky.jl:18
cholesky!(A::Union{Hermitian{T,S}, Hermitian{Complex{T},S}, Symmetric{T,S}} where S where T<:Real) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/cholesky.jl:152
Possible fix, define
cholesky!(::Symmetric{T<:Real,S} where S<:BandedMatrices.BandedMatrix)
Stacktrace:
[1] …
```
=> Cholesky improvements

src/BandedMatrices.jl, src/banded/BandedMatrix.jl, src/lapack.jl, src/symbanded/symbanded.jl, test/test_banded.jl, test/test_symbanded.jl
Actually, the result of #77 returned eigenvectors of symmetric banded matrices as those of the similar `SymTridiagonal` matrices.
In the long run, I feel it would be best to return an eigen-struct uncoupling the band reduction step from the symmetric tridiagonal step. But in the short run, there's no good reason not to override the LAPACK drivers.
=> add LAPACK eigen methods

src/BandedMatrices.jl, src/symbanded/BandedCholesky.jl, src/tribanded.jl, test/test_symbanded.jl
@MikaelSlevinsky Any comments? This uses LinearAlgebra.Cholesky for much cleaner code, and made it easy to generalise.
=> refactor cholesky, support general types

Project.toml, src/BandedMatrices.jl, src/banded/BandedMatrix.jl, src/banded/bandedqr.jl, src/banded/gbmm.jl, src/generic/matmul.jl, test/test_banded.jl, test/test_bandedqr.jl
This is a proof of concept for a new approach to Adaptive QR that is constructed on top of basic building blocks, to be realised in InfiniteLinearAlgebra.jl. I believe this is already much faster than ApproxFun's adaptive QR (which is hack built on BLAS calls).
In the future, a Banded QR leveraging LAPACK may be possible to tackle large bandwidths.
=> Adaptive QR, TNG

src/symbanded/BandedCholesky.jl, test/test_symbanded.jl
This small PR adds a definition of `cholesky` for Hermitian matrices, similar to the existent definition for `Symmetric` matrices.
=> Define cholesky for Hermitian matrices

Project.toml, src/BandedMatrices.jl, src/symbanded/symbanded.jl, src/symbanded/tridiagonalize.jl, test/evaluations.jl, test/test_miscs.jl, test/test_symbanded.jl
Solves #179
A generic algorithm for tridiagonalization has been added, which extends the existing `Symmetric{IEEEFloat}` implementation to complex and big float types.
Performance and accuracy is comparable to the old implementation, which calls LAPACK functions.
=> Added tridiagonalization for symmetric/Hermitian banded matrices

Project.toml, src/generic/AbstractBandedMatrix.jl, test/test_miscs.jl
While procrastinating, I realized I had forgotten about the following case in #189:
``` julia
julia> A = spdiagm(2 => ones(Int, 5))
7×7 SparseMatrixCSC{Int64,Int64} with 5 stored entries:
[1, 3]  =  1
[2, 4]  =  1
[3, 5]  =  1
[4, 6]  =  1
[5, 7]  =  1
julia> BandedMatrix(A)
7×7 BandedMatrix{Int64,Array{Int64,2},Base.OneTo{Int64}}:
⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅
⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅
⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅
⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅
⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1
⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
⋅  ⋅  ⋅  ⋅  ⋅  ⋅
```
=> Improved bandwidths(::SparseMatrixCSC) for purely upper/lower matrices

Project.toml, src/BandedMatrices.jl, src/banded/dot.jl, test/runtests.jl, test/test_dot.jl
This PR ensures that only the non-zero elements of `A`, and hence the only the correct subranges of `x` and `y` are looped over. For matrices with a a single, constant diagonal from `FillArrays`, such as the ones we get from the restriction matrices in ContinuumArrays.jl, it reduces to a dot product between views of `x` and `y`.
The benchmarks are more impressive for larger matrices, but you get the idea:
```julia
julia> (m,n,l) = (1000,150,5)
(1000, 150, 5)
julia> S = BandedMatrices._BandedMatrix(0.1Ones{Int}(1,n), Base.OneTo(m), l, -l)
1000×150 BandedMatrix{Float64,Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}},Base.OneTo{Int64}}:
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ …
```
=> Specialize dot(x, A::BandedMatrix, y)

docs/src/index.md
Added a sentence to the docs mentioning the exported `colrange` and `rowrange`.
=> mention colrange and rowrange in docs

README.md
The [latest document](https://juliamatrices.github.io/BandedMatrices.jl/latest/) is not the latest. This PR fixes the URLs to `dev` instead of `latest`.
=> Fix urls in README.md

.github/workflows/ci.yml, Project.toml, src/BandedMatrices.jl
In https://github.com/JuliaLang/julia/pull/44360, `BLAS.libblas` and `LAPACK.liblapack` were removed. Thus BandedMatrices does not work with Julia nightlies currently, which causes test errors e.g. in PDMats (see e.g. https://github.com/JuliaStats/PDMats.jl/runs/6696362323?check_suite_focus=true).
https://github.com/JuliaLang/julia/pull/44379 added `Base.libblas_name` and `Base.liblapack_name` which can be used instead (see https://github.com/FluxML/NNlib.jl/pull/396 and https://github.com/FluxML/NNlib.jl/pull/396#issuecomment-1058364057).
=> Fix Julia master

Project.toml, src/symbanded/bandedeigen.jl, src/symbanded/symbanded.jl, test/test_symbanded.jl
Implement `copyto!` for symmetric banded matrices. The new function is then used in `eigvals` and `eigen`. The following works with this change:
```julia
julia> A = BandedMatrix(0=>ones(5), 3=>ones(2))
5×5 BandedMatrix{Float64} with bandwidths (0, 3):
1.0  0.0  0.0  1.0   ⋅ 
⋅   1.0  0.0  0.0  1.0
⋅    ⋅   1.0  0.0  0.0
⋅    ⋅    ⋅   1.0  0.0
⋅    ⋅    ⋅    ⋅   1.0
julia> B = BandedMatrix(-1=>ones(4), 0=>2ones(5), 1=>ones(4))
5×5 BandedMatrix{Float64} with bandwidths (1, 1):
2.0  1.0   ⋅    ⋅    ⋅ 
1.0  2.0  1.0   ⋅    ⋅ 
⋅   1.0  2.0  1.0   ⋅ 
⋅    ⋅   1.0  2.0  1.0
⋅    ⋅    ⋅   1.0  2.0
julia> SA = Symmetric(A, :L)
5×5 Symmetric{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}}:
1.0   ⋅    ⋅    ⋅    ⋅ 
⋅   1.0   ⋅    ⋅    ⋅ 
⋅    ⋅   1.0   ⋅    ⋅ 
⋅    ⋅    ⋅   1.0 …
```
=> `eigen` for `Symmetric` with mismatched parent bandwidths

.github/workflows/ci.yml
Now that v1 points to v1.8, this was duplicating the test
=> Don't test on v1.8 explicitly

.github/workflows/ci.yml
Since the CI tests are run for a PR anyway, this will avoid duplicate CI runs if a PR includes push to a branch on the repo. The only difference will pushing to branches without creating a PR to master won't trigger the CI.
=> Run CI only on push to master

Project.toml, src/banded/BandedMatrix.jl, test/test_linalg.jl
Also compute the `k-th` diagonal
After this:
```julia
julia> B = BandedMatrix(1=>[1:5;], 2=>fill(2,4))
6×6 BandedMatrix{Int64} with bandwidths (-1, 2):
⋅  1  2  ⋅  ⋅  ⋅
⋅  ⋅  2  2  ⋅  ⋅
⋅  ⋅  ⋅  3  2  ⋅
⋅  ⋅  ⋅  ⋅  4  2
⋅  ⋅  ⋅  ⋅  ⋅  5
⋅  ⋅  ⋅  ⋅  ⋅  ⋅
julia> diag(B)
6-element Vector{Int64}:
0
0
0
0
0
0
julia> diag(B, 1)
5-element Vector{Int64}:
1
2
3
4
5
```
=> Fix `diag` if data excludes the principal diagonal

src/banded/BandedLU.jl
I didn't check, but unbound type parameters often cause performance issues, so this may not be merely cosmetic.
=> remove unbound type parameter

Project.toml, README.md, src/banded/BandedLU.jl, test/runtests.jl
Removes an unbound type parameter in a `_lu` method.
=> Use `Aqua` to ensure project quality

.github/workflows/TagBot.yml
Copied from https://github.com/JuliaRegistries/TagBot#setup. @hyrodium let's see if this helps in any way with tagbot being able to run the documenter action
=> Update tagbot with write permission

Project.toml, src/BandedMatrices.jl, src/symbanded/BandedCholesky.jl
https://github.com/JuliaLang/julia/pull/47063 "broke" `cholesky` of banded matrices, as it uses 3-arg `similar` for the copy. This fixes it.
It also includes some clean-up about which methods are only used and which ones are overloaded.
=> Make `cholesky` work on v1.9

Project.toml, test/test_symbanded.jl
Adjusts tests to the generalizations in https://github.com/JuliaLang/julia/pull/47107, which make the tests pass.
=> Turn broken `ldiv` tests to proper tests

src/generic/broadcast.jl, test/test_broadcasting.jl
Using an inplace map instead of inplace broadcasting seems to lead to better performance, for reasons that aren't fully clear to me
On Julia v1.8.3
master:
```julia
julia> using BandedMatrices, BenchmarkTools
julia> B = BandedMatrix(0 => rand(1000), 1=>rand(999), -2=>rand(998));
julia> @btime $B + $B;
6.585 μs (3 allocations: 31.34 KiB)
```
this PR
```julia
julia> @btime $B + $B;
4.952 μs (3 allocations: 31.34 KiB)
```
On julia v1.9.0-alpha1
this PR
```julia
julia> @btime $B + $B;
2.900 μs (3 allocations: 31.34 KiB)
```
while the performance on master is similar.
Edit: this may be due to subpar code generation on my laptop, so I'll check on other systems as well.
=> Use `map!` in broadcasting if sizes match

src/generic/matmul.jl, test/test_banded.jl
We may avoid recursion in `_banded_muladd!` and directly call `_banded_gbmv!`instead. This makes type-inference easier, and reduces TTFX. 
On master
```julia
julia> B = BandedMatrix(0=>ones(1000));
julia> v = zeros(size(B,2));
julia> @time B * v;
1.007807 seconds (2.95 M allocations: 193.016 MiB, 7.89% gc time, 182.64% compilation time)
```
This PR
```julia
julia> @time B * v;
0.294613 seconds (647.92 k allocations: 42.859 MiB, 5.88% gc time, 151.79% compilation time)
```
Tests for `BlockBandedMatrices`, `ApproxFunBase`, `ApproxFunOrthogonalPolynomials` and `ApproxFun` pass locally for me with this PR. This also resolves the issue with precompiling `B * v` in https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/pull/283#issuecomment-1379893550
=> Avoid recursion in `_banded_muladd!` for vectors

src/BandedMatrices.jl, src/banded/BandedMatrix.jl
A simpler alternative to https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/pull/283, without the need for extra packages, and one that seems to work almost as well for many cases.
After this, the time to first execution practically disappears for addition and subtraction for the common use case where the parent is a `Matrix{Float64}`
```julia
julia> using BandedMatrices
julia> B = BandedMatrix(0=>ones(1000));
julia> @time B + B;
0.000110 seconds (63 allocations: 11.375 KiB)
```
Some others aren't completely eliminated, but considerably improved:
```julia
julia> v = ones(size(B,2));
julia> @time @eval B * v;
0.009193 seconds (8.87 k allocations: 556.567 KiB)
```
=> Precompile instructions for basic algebra operations

src/generic/broadcast.jl, test/test_broadcasting.jl
Some bugfixes in `_banded_broadcast!` for matrix arguments. Stuff like the following work correctly now: 
```julia
julia> n = 4
4
julia> (l, u) = (2, -2)
(2, -2)
julia> A = brand(n,n,l,u)
4×4 BandedMatrix{Float64} with bandwidths (2, -2):
⋅         ⋅         ⋅    ⋅ 
⋅         ⋅         ⋅    ⋅ 
0.200725   ⋅         ⋅    ⋅ 
⋅        0.676815   ⋅    ⋅ 
julia> A - I
4×4 BandedMatrix{Float64} with bandwidths (2, 0):
-1.0         ⋅          ⋅     ⋅ 
0.0       -1.0         ⋅     ⋅ 
0.200725   0.0       -1.0    ⋅ 
⋅         0.676815   0.0  -1.0
```
=> Fix broadcast indexing for two matrices

src/generic/broadcast.jl, test/test_linalg.jl
Evaluate `B * D` as `B.data .* D.diag'` instead of `B  .* D.diag'`. This helps with vectorization, leading to significant performance improvements.
With arrays
```julia
julia> A = BandedMatrix(0=>Float64[1:3000;]); D = Diagonal(A);
julia> A2 = brand(3000, 3000, 200,200); D2 = Diagonal(A2);
``` 
we obtain
| Operation | Master | PR |
| --- | :-: | :-: |
| `A * D` | 54.393 μs | 2.574 μs |
| `A2 * D2` | 2.252 ms | 1.232 ms |
I've specialized the method for `DenseColumnMajor` layout. It may work with other layouts as well, but this is a conservative first step.
=> Specialize BandedMatrix * Diagonal for DenseColumnMajor

src/banded/BandedMatrix.jl, src/interfaceimpl.jl, test/test_banded.jl, test/test_interface.jl
While converting from an `AbstractMatrix` to a `BandedMatrix`, we may use a faster path if the argument is banded and has a `BandedColumns{DenseColumnMajor}()` memory layout .
On master
```julia
julia> D = Diagonal(rand(1000));
julia> @btime convert(BandedMatrix, $D);
4.521 μs (4 allocations: 8.11 KiB)
julia> @btime BandedMatrix{Float32}($D);
4.588 μs (2 allocations: 4.11 KiB)
julia> @btime BandedMatrix($D);
2.396 μs (2 allocations: 7.98 KiB)
```
This PR
```julia
julia> @btime convert(BandedMatrix, $D);
759.925 ns (6 allocations: 8.20 KiB)
julia> @btime BandedMatrix{Float32}($D);
564.160 ns (4 allocations: 4.20 KiB)
julia> @btime BandedMatrix($D);
641.483 ns (4 allocations: 8.06 KiB)
```
With some refactoring, all of these could become equally performant.
TBH I'm a bit surprised that this …
=> Check `isbanded` in conversions

.github/workflows/downstream.yml
Given that this package is fairly fundamental in the ecosystem, it would be good to test some downstream packages against PRs to ensure that they aren't breaking. At the moment, I've added a test against `BlockBandedMatrices.jl`.
This test is automatically skipped on breaking releases of this package, or if the package version resolution fails for some reason.
=> Test downstream packages

src/generic/AbstractBandedMatrix.jl, test/test_interface.jl
It's useful to know that some matrix types don't implement the `BandedMatrix` interface, and this does not need to error like it does at present.
After this PR:
```julia
julia> isbanded(rand(3,3))
false
```
This errors on master.
=> Add `isbanded` fallback

Project.toml, docs/Project.toml, docs/make.jl, docs/src/index.md, src/generic/Band.jl, test/runtests.jl
Change `AbstractUnitRange` → `StepRange` in the docstring of `BandSlice`, since `diagind` returns a step range. Also, fix some outdated docstring errors and add compat bounds to the documentation project.
=> Update `BandSlice` docstring and fix docs

src/generic/broadcast.jl
On master
```julia
julia> B = BandedMatrix(1=>Float64.(1:3000));
julia> @btime $B .* 2;
8.533 μs (3 allocations: 23.59 KiB)
```
This PR
```julia
julia> @btime $B .* 2;
2.560 μs (7 allocations: 23.77 KiB)
```
=> Broadcast numbers over vec(data)

.github/workflows/ci.yml
The older versions are deprecated, and this should get rid of the CI warnings
=> Update CI actions to v3

Project.toml, src/BandedMatrices.jl, src/banded/BandedLU.jl, src/banded/linalg.jl, src/symbanded/SplitCholesky.jl
This prepares the ground for https://github.com/JuliaLang/julia/pull/46874.
=> Adjust to `AdjointFactorization`

src/generic/broadcast.jl, test/test_broadcasting.jl
This helps with performance in `A .* b` type cases
With arrays
```julia
A = BandedMatrix(0=>Float64[1:3000;]); v = rand(size(A,1));
```
| Operation | Master | PR |
| --- | :-: | :-: |
| `A .* v` | 50.560 μs | 19.609 μs |
| `v .* A` | 49.867 μs | 23.308 μs |
| `A .* v'` | 51.944 μs| 10.112 μs |
| `v' .* A` | 58.198 μs| 10.388 μs |
=> Bandwidth-preserving branches in row/col broadcast

src/generic/Band.jl, src/generic/broadcast.jl, test/test_broadcasting.jl
Currently, on master,
```julia
julia> D = brand(4, 4, -2, 1) # empty
4×4 BandedMatrix{Float64} with bandwidths (-2, 1):
⋅    ⋅    ⋅    ⋅ 
⋅    ⋅    ⋅    ⋅ 
⋅    ⋅    ⋅    ⋅ 
⋅    ⋅    ⋅    ⋅ 
julia> B = brand(size(D)...,1,2) # non-empty and non-zero bands
4×4 BandedMatrix{Float64} with bandwidths (1, 2):
0.867543  0.104975  0.812628   ⋅ 
0.954679  0.96598   0.396831  0.427929
⋅        0.457686  0.563948  0.429046
⋅         ⋅        0.258889  0.308205
julia> D .= B # errors correctly
ERROR: attempt to access BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}} with bandwidths (-2, 1) at band 0
Stacktrace:
[1] checkzerobands(dest::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, f::typeof(identity), A::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}})
@ …
```
=> Throw error in broadcasting to fewer bands

src/generic/broadcast.jl
To check for zero values, we only need to check the filled bands, and not all columns.
On master
```julia
julia> B = brand(1,1000,0,1); B .= 0; B
1×1000 BandedMatrix{Float64} with bandwidths (0, 1):
0.0  0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
julia> C = brand(size(B)...,0,0); C .= 0; C
1×1000 BandedMatrix{Float64} with bandwidths (0, 0):
0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
julia> @btime BandedMatrices.checkzerobands($C, *, $B);
3.792 μs (0 allocations: 0 bytes)
julia> @btime $C .= $B;
3.905 μs (0 …
```
=> rowsupport in indexing in checkzerobands

src/generic/broadcast.jl, test/test_broadcasting.jl
Also, short-circuit trivial cases where either the source or the destination is empty
=> Rowsupport in banded axpy methods

src/generic/broadcast.jl, test/test_broadcasting.jl
On master
```julia
julia> B = brand(1,4,0,1)
1×4 BandedMatrix{Float64} with bandwidths (0, 1):
0.743297  0.461126   ⋅    ⋅ 
julia> C = brand(size(B)...,0,0)
1×4 BandedMatrix{Float64} with bandwidths (0, 0):
0.172887   ⋅    ⋅    ⋅ 
julia> C' .= B'; C
1×4 BandedMatrix{Float64} with bandwidths (0, 0):
0.743297   ⋅    ⋅    ⋅ 
```
This PR fixes this, and this throws an error now, as it should.
```julia
julia> C' .= B'
ERROR: BandError: attempt to access Adjoint{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}} with bandwidths (0, 0) at band -1
```
=> Fallback function broadcast zero check

src/generic/broadcast.jl
On master
```julia
julia> B = brand(2,1000,1,0);
julia> C = brand(size(B)..., bandwidths(B)...);
julia> D = zero(C);
julia> @btime BandedMatrices.checkzerobands($D, *, ($B,$C));
4.204 μs (0 allocations: 0 bytes)
```
This PR
```julia
julia> @btime BandedMatrices.checkzerobands($D, *, ($B,$C));
34.958 ns (0 allocations: 0 bytes)
```
Also, on master:
```julia
julia> B = brand(2,1000,1,80);
julia> C = brand(size(B)..., (bandwidths(B) .+ 1)...);
julia> @btime BandedMatrices.checkzerobands($C, identity, $B);
329.283 ns (0 allocations: 0 bytes)
```
This PR
```julia
julia> @btime BandedMatrices.checkzerobands($C, identity, $B);
7.126 ns (0 allocations: 0 bytes)
```
=> rowsupport in checkzerobands for two matrices

.github/workflows/ci.yml
This skips identical CI tests (e.g. on merging a PR), which can reduce the load on CI resources, and accelerate development. This also cancels existing tests in favor of new ones if successive commits are pushed rapidly, which is often what one wants if the second commit is a bugfix for the first.
=> Skip duplicate CI tests

src/generic/broadcast.jl, test/test_broadcasting.jl
This makes `A .* v'` and `A .* permutedims(v)` equally performant.
=> Fast path for DenseColumnMajor row broadcast

src/generic/broadcast.jl
Preserving the memory layouts might let us come up with optimized methods in the future
=> Preserve memory layouts in special banded broadcast

src/BandedMatrices.jl, src/generic/broadcast.jl
Bugfixes in untested branches of `__right_rowvec_banded_broadcast` and `__left_rowvec_banded_broadcast`, and a bandwidth-matching branch in `__banded_broadcast` which helps with performance.
On master
```julia
julia> B = brand(5000,5000,0,0);
julia> @btime $B' .+ $B';
113.291 μs (3 allocations: 39.16 KiB)
```
This PR
```julia
julia> @btime $B' .+ $B';
44.939 μs (3 allocations: 39.16 KiB)
```
Some redundant precompile statements are removed.
=> Matching bandwidth branch in banded broadcast

src/generic/broadcast.jl
Now that `A .* v'` is fast, specializing `A * D` is largely unnecessary. The performance would be improved further by https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/pull/118.
=> Remove Rmul Diagonal specialization

.github/workflows/docs.yml, Project.toml, docs/make.jl, src/BandedMatrices.jl, src/banded/BandedMatrix.jl, src/generic/Band.jl, test/runtests.jl
The type `BandedMatrixBand` wasn't defined properly, so the `dataview` function was never being hit. This fixes the dispatch and improves performance.
On master
```julia
julia> B = BandedMatrix(0=>rand(1000));
julia> @btime $B[band(0)];
9.535 μs (1 allocation: 7.94 KiB)
```
This PR
```julia
julia> @btime $B[band(0)];
971.582 ns (1 allocation: 7.94 KiB)
```
Also, removed a bunch of unnecessary `convert` methods
=> Faster band indexing for BandedMatrix

src/banded/BandedMatrix.jl
The `IndexStyle` defined in this package in unnecessary, and was not being hit in any case.
=> don't specialize IndexStyle

src/banded/BandedMatrix.jl, src/generic/broadcast.jl, test/test_broadcasting.jl
If the bandwidths match, we may forward `axpy!` to the data, which is faster:
On master
```julia
julia> B = brand(400,400,20,20);
julia> C = brand(400,400,20,20);
julia> @btime axpy!(2.0, $B, $C);
10.996 μs (0 allocations: 0 bytes)
```
This PR
```julia
julia> @btime axpy!(2.0, $B, $C);
3.171 μs (0 allocations: 0 bytes)
```
The other cases may also be forwarded, but that can be a separate PR.
=> `axpy!` for BandedMatrix

Project.toml, src/generic/Band.jl, test/test_indexing.jl
This is necessary to prevent views of band-views from allocating a vector of indices.
On master
```julia
julia> A = BandedMatrix(0=>1:4, 1=>(1:3) .+ 5, -1=>(1:3) .+ 10)
4×4 BandedMatrix{Int64} with bandwidths (1, 1):
1   6   ⋅  ⋅
11   2   7  ⋅
⋅  12   3  8
⋅   ⋅  13  4
julia> v = @view A[band(1)]
3-element view(reshape(::BandedMatrix{Int64, Matrix{Int64}, Base.OneTo{Int64}}, 16), BandSlice(Band(1), 5:5:15)) with eltype Int64:
6
7
8
julia> w = view(v, 2:3)
2-element view(reshape(::BandedMatrix{Int64, Matrix{Int64}, Base.OneTo{Int64}}, 16), [10, 15]) with eltype Int64:
7
8
```
The `parentindices` of `w` is a vector. This is terrible for performance, as in-place broadcasting will perform unaliasing, which will repeatedly keep copying the vector.
This PR
```julia
julia> w = view(v, 2:3) …
```
=> Generalize indexing a BandSlice

src/generic/matmul.jl
This improves type-inference, and removes an allocation in `BandedMatrix * Vector`.
```julia
julia> B = brand(4000, 4000, 5, 5); v = rand(size(B,2)); w = copy(v);
julia> @btime ((v,B,w) -> mul!(view(w,:), B, view(v,:)))($v,$B,$w);
23.250 μs (1 allocation: 48 bytes) # master
23.238 μs (0 allocations: 0 bytes) # PR
```
=> `unalias` in `_banded_gbmv!`

Project.toml, src/generic/matmul.jl, test/test_linalg.jl
This PR avoids hitting `default_blasmul` and uses `gbmv` in evaluating `B::BandedMartix * X::Matrix`, by looping over the columns. The approach is naive, but this is already significantly better than the fallback.
```julia
julia> B = brand(4000, 4000, 5, 5); X = rand(size(B)...);
julia> @btime $B * $X;
970.386 ms (2 allocations: 122.07 MiB) # master
161.312 ms (2 allocations: 122.07 MiB) # PR
```
This PR requires https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/pull/131 to be merged first for optimal performance, otherwise the 5-argument matrix-vector `mul!` becomes very slow.
I've made the method very specific for now, but this may be relaxed along with more tests.
=> Use gbmv in banded*dense

src/generic/matmul.jl
On master
```julia
julia> B = brand(Int, 1, 1000, 1, 1);
julia> v = rand(size(B,1));
julia> w = rand(size(B,2));
julia> @btime $B' * $v;
3.200 μs (1 allocation: 7.94 KiB)
julia> @btime $B * $w;
3.440 μs (1 allocation: 64 bytes)
```
This PR
```julia
julia> @btime $B' * $v;
762.748 ns (1 allocation: 7.94 KiB)
julia> @btime $B * $w;
78.934 ns (1 allocation: 64 bytes)
```
=> `rowsupport` in `MatMulVecAdd` materialize

src/symbanded/bandedeigen.jl, test/test_symbanded.jl
Fix https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/issues/346 by following the suggestion in https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/issues/346#issuecomment-1516543380, except the temporary vectors are stored in the struct to avoid reallocating them on every access. One of the vectors may be replaced by a `OneElement` after https://github.com/JuliaArrays/FillArrays.jl/pull/241 is merged.
After this,
```julia
julia> @time λ,Q = eigen(Symmetric(brand(1000, 1000, 4, 4)));
0.199235 seconds (58 allocations: 27.075 MiB)
julia> @btime $Q[1,1];
1.929 ms (0 allocations: 0 bytes)
```
=> Faster `getindex` for `BandedEigenvectors`

.github/workflows/ci.yml
Now that v1 points to v1.9, this is unnecessary
=> remove explicit test on v1.9

Project.toml, src/BandedMatrices.jl, src/symbanded/bandedeigen.jl
This provides a slight improvement in performance and reduction in allocations on `FillArrays` v1.0.1 and above.
In https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/pull/354, we had
```julia
julia> @time λ,Q = eigen(Symmetric(brand(1000, 1000, 4, 4)));
0.199235 seconds (58 allocations: 27.075 MiB)
julia> @btime $Q[1,1];
1.929 ms (0 allocations: 0 bytes)
``` 
After this,
```julia
julia> @time λ,Q = eigen(Symmetric(brand(1000, 1000, 4, 4)));
0.189025 seconds (58 allocations: 27.067 MiB)
julia> @btime $Q[1,1];
1.462 ms (0 allocations: 0 bytes)
```
=> `OneElement` in `getindex` for `BandedEigenvectors`

Project.toml, src/lapack.jl, src/symbanded/bandedeigen.jl, src/symbanded/symbanded.jl, src/symbanded/tridiagonalize.jl, test/test_symbanded.jl
After this,
```julia
julia> A = Hermitian(brand(ComplexF64, 6, 6, 2, 2))
6×6 Hermitian{ComplexF64, BandedMatrix{ComplexF64, Matrix{ComplexF64}, Base.OneTo{Int64}}}:
0.539725+0.0im          0.25559+0.00579831im  0.559341+0.114413im            ⋅                      ⋅                      ⋅    
0.25559-0.00579831im  0.784935+0.0im         0.378323+0.837163im   0.337384+0.392795im             ⋅                      ⋅    
0.559341-0.114413im    0.378323-0.837163im    0.744348+0.0im        0.153074+0.0727464im   0.420417+0.0808449im            ⋅    
⋅             0.337384-0.392795im    0.153074-0.0727464im  0.267722+0.0im         0.377242+0.541864im    0.690377+0.470517im
⋅                      ⋅             0.420417-0.0808449im  0.377242-0.541864im     0.67322+0.0im …
```
=> In-place eigvals for complex Hermitian `BandedMatrix`

src/generic/AbstractBandedMatrix.jl
This reverts #227 on older Julia versions, as `lu` doesn't seem to have methods defined for `Adjoint` on Julia v1.6
=> restrict Adjoint copy to v1.9+

src/symbanded/bandedeigen.jl, test/test_symbanded.jl
Fix the multiplication `Matrix(A)*Q` in
```julia
julia> A = Symmetric(brand(Float64, 5, 5, 2, 4));
julia> F = eigen(A, 2:4);
julia> Λ, Q = F;
julia> Matrix(A) * Q
ERROR: DimensionMismatch: A has size (3,10), B has size (10,10), C has size (10, 3)
```
This PR
```julia
julia> Matrix(A) * Q
5×3 Matrix{Float64}:
-0.215735   -0.0048621   0.543025
0.481573    0.0179861   0.0938919
-0.1956      0.093253   -0.308269
-0.0523172  -0.198675   -0.19431
-0.0175463   0.106258   -0.0838154
```
=> Fixes to mul for BandedEigenvectors

src/symbanded/bandedeigen.jl, test/test_symbanded.jl
Similar to https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/pull/354. This PR introduces an abstract type `AbstractBandedEigenvectors` and defines the indexing for that, so that its subtypes `BandedEigenvectors` and `BandedGeneralizedEigenvectors` may share the behavior. A `BandedGeneralizedEigenvectors` may reuse the scratch vector in the enclosed `BandedEigenvectors`, so no extra allocation is necessary.
After this,
```julia
julia> A = Symmetric(brand(Float64, 6, 6, 2, 4));
julia> B = Symmetric(BandedMatrix(0=>Float64.(1:6)));
julia> Λ, V = eigen(A, B);
julia> @btime $V[1,1];
96.803 ns (0 allocations: 0 bytes)
```
whereas, on master,
```julia
julia> @btime $V[1,1];
377.146 ns (1 allocation: 368 bytes)
```
=> Faster indexing for `BandedGeneralizedEigenvectors`

src/lapack.jl, src/symbanded/SplitCholesky.jl, src/symbanded/bandedeigen.jl, src/symbanded/symbanded.jl, src/symbanded/tridiagonalize.jl, test/test_symbanded.jl
```julia
julia> A = Hermitian(brand(ComplexF64, 6, 6, 2, 2));
julia> B = Hermitian(BandedMatrix(0=>ComplexF64.(1:6)));
julia> λb = @btime eigvals($A, $B); # This PR
3.415 μs (13 allocations: 1.73 KiB)
julia> λ = @btime eigvals($(Hermitian(Matrix(A))), $(Hermitian(Matrix(B))));
7.220 μs (10 allocations: 1.98 KiB)
julia> λb ≈ λ
true
```
=> Generalized eigen for complex Hermitian BandedMatrix

Project.toml, src/banded/BandedMatrix.jl, test/test_banded.jl
Forwarding the broadcasting to the data matrix makes it much more efficient:
```julia
julia> B = brand(Int8, 200, 200, -2, 2);
julia> @btime $B[band(2)] .= 3;
83.740 ns (0 allocations: 0 bytes) # PR
1.223 μs (0 allocations: 0 bytes) # master
```
=> broadcast value to an entire band

Project.toml, src/banded/BandedMatrix.jl, test/test_banded.jl, test/test_broadcasting.jl
After this PR
```julia
julia> B = brand(Int, 200, 200, 20, 20);
julia> @btime $B[band(2)] .= 1:198;
204.381 ns (0 allocations: 0 bytes) # PR (improvement because of copyto implementation)
978.750 ns (0 allocations: 0 bytes) # master
julia> @btime $B[band(2)] = 1:198;
117.487 ns (0 allocations: 0 bytes) # PR (improvement becasue of inbounds)
152.594 ns (0 allocations: 0 bytes) # master
```
Also, ensures that `setindex!` returns the array and not the value. This matches the `Base` behaviour.
```julia
julia> setindex!(zeros(2,2), 1, 1)
2×2 Matrix{Float64}:
1.0  0.0
0.0  0.0
julia> setindex!(fill!(brand(Float64,2,2,1,1),0), 1, 1)
2×2 BandedMatrix{Float64} with bandwidths (1, 1):
1.0  0.0
0.0  0.0
```
=> Broadcast a vector to a band

Project.toml, src/banded/BandedMatrix.jl, test/test_broadcasting.jl
After this,
```julia
julia> B = brand(Int, 200, 200, 20, 20);
julia> @btime $B[band(2)] .= 2 .* $v .+ 4;
237.988 ns (0 allocations: 0 bytes) # PR
1.149 μs (0 allocations: 0 bytes) # master
```
=> Faster broadcasting for band view

src/banded/BandedMatrix.jl
Replace `Base.getindex` with `getindex`, which makes it easy to search for this
=> Extend getindex without Base namespace consistently

src/banded/BandedMatrix.jl, src/generic/Band.jl
```julia
julia> B = brand(Int, 200, 200, 20, 20);
julia> @btime $B[1,BandRange] = 1:21;
29.909 ns (0 allocations: 0 bytes) # PR
62.717 ns (0 allocations: 0 bytes) # master
julia> @btime $B[BandRange,1] = 1:21;
34.899 ns (0 allocations: 0 bytes) # PR
57.282 ns (0 allocations: 0 bytes) # master
```
The improvements are mainly due to fewer checks. The performances are identical if `@inbounds` is specified.
=> optimized setindex methods

src/banded/BandedMatrix.jl, test/test_indexing.jl
```julia
julia> B = brand(Int, 200, 200, 20, 20);
julia> @btime $B[BandRange,1];
53.515 ns (1 allocation: 224 bytes) # PR
101.435 ns (1 allocation: 224 bytes) # master
julia> @btime $B[1,BandRange];
75.047 ns (1 allocation: 224 bytes) # PR
99.042 ns (1 allocation: 224 bytes) # master
```
Similarly, with a `Colon` as one of the indices. The improvement comes from forwarding the indexing to the data.
=> Optimized row/col getindex for a `BandedMatrix`

Project.toml, src/interfaceimpl.jl, test/test_interface.jl
This PR changes `getindex(::Diagonal, ::Band)` and similar for other structured matrix types from `LinearAlgebra`, and simply returns the corresponding `diag`. This fixes cases where the type-promotion is complicated, and in any case, this is much simpler to maintain. The `diag` methods should be implemented by the corresponding array types, e.g. in `FillArrays`.
After this, the following works:
```julia
julia> E = Eye(4)
4×4 Eye{Float64}
julia> E[band(0)]
4-element Vector{Float64}:
1.0
1.0
1.0
1.0
julia> E[band(1)]
3-element Vector{Float64}:
0.0
0.0
0.0
```
whereas the latter errors on master. After https://github.com/JuliaArrays/FillArrays.jl/pull/270, these will return `Fill`s.
=> consistent band indexing for structured matrices

Project.toml, src/generic/Band.jl
On master
```julia
julia> A = zeros(10,10);
julia> r = first(to_indices(A, (band(1),)));
julia> @btime @inbounds $r[1:end];
19.346 ns (0 allocations: 0 bytes)
```
After this PR,
```julia
julia> @btime @inbounds $r[1:end];
13.774 ns (0 allocations: 0 bytes)
```
=> `@propagate_inbounds` in indexing a `BandSlice`

Project.toml, src/interfaceimpl.jl, test/test_interface.jl
After this, the following works:
```julia
julia> D = Diagonal(Ones(4));
julia> D[Band(0)]
4-element Fill{Float64}, with entries equal to 1.0
julia> D[Band(-1)]
3-element Fill{Float64}, with entries equal to 0.0
```
This doesn't work on master, as `Zeros` can't be converted to `Ones`. The case with `Fill` bands is special-cased in this PR, although a more general would be ideal in the longer term.
This also adds band indexing tests for infinite structured matrices.
=> Band indexing for structured matrices with Fill bands

Project.toml, src/precompile.jl
Given that 32-bit CPU arrays are perhaps not widely used at present, it's unnecessary to precompile and cache code for this case. Not doing so would shave off 0.15s from the package load time.
=> don't precompile for Float32/ComplexF32

src/BandedMatrices.jl
The `Base.libblas_name` bindings have been deprecated for a long time, don't use those.
=> Use `LinearAlgebra.BLAS.libblas`

Project.toml, src/lapack.jl, test/test_symbanded.jl, test/test_tribanded.jl
Fix https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/issues/100
This mirrors the behavior in `LinearAlgebra`, and after this, the following are consistent:
```julia
julia> B = BandedMatrix(-3=> 2ones(2), -1=>ones(4), 0=>2ones(5)); Buplo = :L; SB = Symmetric(B, Buplo);
julia> cholesky(Matrix(SB), check = false)
Failed factorization of type Cholesky{Float64, Matrix{Float64}}
julia> cholesky(SB, check = false)
Failed factorization of type Cholesky{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}}
```
=> Don't throw in cholesky if check=false

Project.toml, src/generic/matmul.jl, test/test_linalg.jl
This helps in cases where `B` is also sparse and banded. The use case that I have in mind is `OneElement` vectors, which have only a single populated band.
=> Loop over colsupport(vector) in matrix-vector multiplication

src/generic/matmul.jl
Using the type alias `MatMulMatAdd` makes the code easier to read
=> simplify MulAdd type in matmul

Project.toml, src/generic/matmul.jl, test/test_banded.jl
Certain elements of `y` were being set to zero under the incorrect assumption that `beta=0`
Also, consistently perform size-compatibility checks in `materialize!` using `checkdimensions`
=> Fix 5-term mul with non-zero beta

Project.toml, src/banded/BandedMatrix.jl, test/test_miscs.jl
After this PR
```julia
julia> B = BandedMatrix(-1=>1:4, 0=>1:5, 1=>1:4);
julia> show(B)
BandedMatrix(-1 => [1, 2, 3, 4], 0 => [1, 2, 3, 4, 5], 1 => [1, 2, 3, 4])
```
vs on master
```julia
julia> show(B)
[1 1 0 0 0; 1 2 2 0 0; 0 2 3 3 0; 0 0 3 4 4; 0 0 0 4 5]
```
The new display format is more informative, sparse and a valid constructor as well.
=> show for BandedMatrix may print the constructor

src/banded/BandedMatrix.jl, test/test_indexing.jl
This PR uses the fact that views of a `BandedMatrix` with `AbstractUnitRange` ranges have bands that are contiguous views of the original. This helps speed up indexing operations by forwarding these to the `bandeddata`.
On master
```julia
julia> A = brand(200, 200, 3, 4);
julia> B = view(A, 1:100, 1:100);
julia> @btime $B[band(0)];
1.050 μs (1 allocation: 896 bytes)
```
This PR
```julia
julia> @btime $B[band(0)];
214.281 ns (1 allocation: 896 bytes)
```
=> Band views of SubArrays of BandedMatrices

Project.toml, src/generic/Band.jl
Minor change: call `bandwidths` in `checkbandmatch` instead of accessing the fields of the array. This may help in generalizing the function to other `AbstractBandedMatrix` types.
=> Accessor function instead of field access in checkbandmatch

Project.toml, src/BandedMatrices.jl, src/generic/matmul.jl, src/generic/utils.jl, test/test_linalg.jl
This now matches `LinearAlgebra`'s convention of `A * B * alpha + C * beta`, from the current `alpha * A * B + beta * C`.
=> Fix mat * vec with non-commutative numbers

Project.toml, src/banded/BandedMatrix.jl, src/generic/Band.jl, test/test_miscs.jl
On Julia v1.11, `diagind` may return a range of `CartesianIndex`es. This prepares `BandSlice` to accept such ranges.
=> Parameterize BandSlice to accept arbitrary ranges

Project.toml, src/banded/BandedMatrix.jl
Currently, broadcasting is faster than `setindex!` as SIMD gets blocked in the latter  (https://github.com/JuliaLang/julia/issues/40962#issuecomment-1921340377), so this change uses the faster variant. This might need revisiting in the future if `setindex!` becomes significantly faster.
On master
```julia
julia> B = brand(6000,6000,4000,4000);
julia> @btime $B[:, 3];
4.985 μs (4 allocations: 47.00 KiB) # master
3.980 μs (4 allocations: 47.00 KiB) # PR
julia> @btime $B[:, 5000];
5.619 μs (4 allocations: 47.00 KiB) # master
4.462 μs (4 allocations: 47.00 KiB) # PR
```
=> Faster `B[:,i]` for a `BandedMatrix` using broadcasting

Project.toml, src/banded/BandedMatrix.jl, test/test_miscs.jl
After this,
```julia
julia> B = brand(Int8,20,20,7,7);
julia> show(B)
BandedMatrix(-7 => Int8[39, -124, 64, -114, -47, 76, -40, 35, -87, 82, 40, 104, 122], -6 => Int8[49, 3, 72, -83, 84, -89, 65, 11, 3, -81, -29, -54, -80, -24], -5 => Int8[-81, -63, 127, -6, -115, 76, -120, 38, 124, 116, -14, 113, 98, -12, 47], -4 => Int8[-5, 99, -41, 40, -62, 86, -15, -90, 42, -73, -5, -24, 28, 56, 108, -91]  …  4 => Int8[13, 125, -10, -125, -96, 87, -66, 46, 127, -44, -43, 52, -70, 13, -55, -109], 5 => Int8[119, 16, 117, 122, -35, -67, -73, 89, 31, 75, -12, 101, -47, -90, 57], 6 => Int8[107, -112, -77, -57, 16, 86, -62, 52, 48, -31, -61, 26, -19, -93], 7 => Int8[0, -12, 39, 123, 90, 121, -109, 68, 57, -110, -126, -119, -93])
```
Some of the bands are not printed (indicated by `…`), which often vastly …
=> Limit the number of bands printed in showing BandedMatrix

Project.toml, src/banded/gbmm.jl, src/generic/matmul.jl, src/generic/utils.jl
With this, multiplying a `BandedMatrix` by a `OneElementVector`  would be as performant as slicing.
```julia
julia> B = brand(6000,6000,4000,4000); O = OneElement(1, 3, size(B,2));
julia> @btime $B * $O;
3.826 μs (2 allocations: 46.92 KiB)
julia> @btime $B[:,$O.ind...];
4.013 μs (4 allocations: 47.00 KiB)
```
=> Use MulAdd's CZeros to remove duplicate zero-fill

Project.toml, src/banded/BandedMatrix.jl, test/test_banded.jl
This will conform to the commonly used meaning of `parent` for arrays.
=> `parent(::BandedMatrix)` returns the underlying data

Project.toml, src/generic/AbstractBandedMatrix.jl, test/test_banded.jl
On master
```julia
julia> B = BandedMatrix(0=>1:4)
4×4 BandedMatrix{Int64} with bandwidths (0, 0):
1  ⋅  ⋅  ⋅
⋅  2  ⋅  ⋅
⋅  ⋅  3  ⋅
⋅  ⋅  ⋅  4
julia> view(B, Base.IdentityUnitRange(2:4), 1:4)
3×4 view(::BandedMatrix{Int64, Matrix{Int64}, Base.OneTo{Int64}}, Base.IdentityUnitRange(2:4), 1:4) with eltype Int64 with indices 2:4×Base.OneTo(4):
⋅  ⋅  0  ⋅
⋅  ⋅  ⋅  0
⋅  ⋅  ⋅  ⋅
```
This PR
```julia
julia> view(B, Base.IdentityUnitRange(2:4), 1:4)
3×4 view(::BandedMatrix{Int64, Matrix{Int64}, Base.OneTo{Int64}}, Base.IdentityUnitRange(2:4), 1:4) with eltype Int64 with indices 2:4×Base.OneTo(4):
⋅  2  ⋅  ⋅
⋅  ⋅  3  ⋅
⋅  ⋅  ⋅  4
```
=> Fix indexing for offset views of BandedMatrixes

src/generic/AbstractBandedMatrix.jl
`colrange` and `rowrange` should be empty (i.e. having a length of 0) if there is no value in the column/row, so the `max` will be implicit.
=> Simpler row/col length using row/colrange

.github/workflows/docs.yml, test/runtests.jl
This prevents test breakages due to the display of types changing between Julia versions.
=> Test doc on Julia v1.10

test/mymatrix.jl, test/runtests.jl, test/test_banded.jl, test/test_bandedlu.jl, test/test_bandedqr.jl, test/test_broadcasting.jl, test/test_dot.jl, test/test_indexing.jl, test/test_interface.jl, test/test_linalg.jl, test/test_miscs.jl, test/test_subarray.jl, test/test_symbanded.jl, test/test_tribanded.jl
This allows us to easily run one test file without states persisting.
=> Make tests modular

src/banded/BandedLU.jl
Hi, this pr is to add a docstring to `lu!` for banded matrices to warn the user about the need for additional storage in the matrix, as discussed in #197.
=> Docstring for `lu!`

Project.toml, src/symbanded/BandedCholesky.jl, test/test_symbanded.jl
=> Fix layout of `cholesky(Symmetric(view(BandedMatrix)))`

src/banded/BandedMatrix.jl, test/test_indexing.jl
I noticed that the following doesn't work:
```
julia> b = BandedMatrix(Ones(3, 9), (0, 0))
3×9 BandedMatrix{Float64} with bandwidths (0, 0):
1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
⋅   1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
⋅    ⋅   1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
julia> b[:,6]
ERROR: BoundsError: attempt to access 3-element Vector{Float64} at index [1:5]
Stacktrace:
[1] throw_boundserror(A::Vector{Float64}, I::Tuple{UnitRange{Int64}})
@ Base .\abstractarray.jl:737
[2] checkbounds
@ .\abstractarray.jl:702 [inlined]
[3] view
@ .\subarray.jl:179 [inlined]
[4] maybeview
@ .\views.jl:148 [inlined]
[5] dotview
@ .\broadcast.jl:1244 [inlined]
[6] getindex(A::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, ::Colon, j::Int64)
@ BandedMatrices …
```
=> Colon-integer indexing bug

Project.toml, src/banded/BandedMatrix.jl, test/test_indexing.jl
I found a bug with indexing rows of a BandedMatrix whose data matrix is one row:
```
julia> a = BandedMatrix(ones(2,5), (0,0))
2×5 BandedMatrix{Float64} with bandwidths (0, 0):
1.0   ⋅    ⋅    ⋅    ⋅
⋅   1.0   ⋅    ⋅    ⋅
julia> a[1,:]
ERROR: ArgumentError: step cannot be zero
Stacktrace:
[1] steprange_last
@ .\range.jl:338 [inlined]
[2] StepRange
@ .\range.jl:325 [inlined]
[3] range_start_step_length(a::Int64, step::Int64, len::Int64)
@ Base .\range.jl:216
[4] _range
@ .\range.jl:168 [inlined]
[5] range
@ .\range.jl:147 [inlined]
[6] data_rowrange
@ d:\Documents\Github\BandedMatrices.jl\src\banded\BandedMatrix.jl:575 [inlined]
[7] getindex(A::BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, k::Int64, ::Colon)
@ BandedMatrices …
```
=> data_rowrange bug

.github/workflows/ci.yml
Currently, we specify the arch as `x64`, but the macos tests are run on `arm64` platforms. It's perhaps best to leave this implicit so that the correct defaults are used.
=> Don't specify arch in ci matrix

Project.toml, src/BandedMatrices.jl
Since this is the LTS now, we don't need to explicitly support v1.6 anymore. Versions of this package <v1.8 would continue to be compatible with julia v1.6.
=> Focus development on julia v1.10+

src/banded/BandedMatrix.jl
Profiling shows that this saves some time in matrix-vector multiplications.
```julia
julia> B = brand(100, 100, 0, 0);
julia> v = rand(size(B,2));
julia> w = similar(v, size(B,1));
julia> @btime mul!($w, $B, $v);
763.242 ns (0 allocations: 0 bytes) # master
698.709 ns (0 allocations: 0 bytes) # This PR
```
=> Define `dataids` for a `BandedMatrix`

src/banded/BandedMatrix.jl, test/test_banded.jl
This might help with certain unaliasing operations, as `unaliascopy` requires the type of the matrix to be preserved.
=> Specialize `unaliascopy` for a `BandedMatrix`
